### ISSUE TITLE
본인 인증 문자에 [드림시큐리티]라고 옵니다. [에이락] 또는 [에이락월렛]으로 변경해 주세요.

### ISSUE THREAD

**Issue by a-fun** [alockwallet/app#1]
![IMG_91DC3E489C46-1](https://user-images.githubusercontent.com/83636017/125715949-097beb3f-4e91-4be9-b23b-4f6855f2adf8.jpeg)

**Comment by gomsugy** [comment]
이 문제는 오류가 아닙니다.
[드림시큐리티] 는 본인인증을 요청한 서비스의 이름이 표시되는 곳이 아닙니다.
본인인증 문자에 드림시큐리티라고 표시되는 것은, (주)드림시큐리티 에서 제공하는 휴대폰본인확인서비스를 사용하기 때문입니다.
어느 서비스에서 본인확인 요청을 하더라도, 본인인증 문자에는 [드림시큐리티] 로 시작하는 문자가 전송됩니다.
-드림시큐리티 우정민-
