### ISSUE TITLE
안드로이드 ) 리워드> 고객사 리스트가 새로고침을 해야지 보입니다.

### ISSUE THREAD

**Issue by hw-afun** [alockwallet/app#10]
앱 실행,앱 호출, 월렛 앱의 탭 중 리워드를 제외한 다른탭에서 리워드 탭을 눌렀을때 연결된 고객사와 보유토큰이 보이지않고 새로고침을 해야지 보입니다.

https://user-images.githubusercontent.com/83437574/130724185-adaa6b97-4313-487e-9552-0a87b1559a28.mp4

이슈 영상 :https://drive.google.com/file/d/1MtKbC7iSqVWCa3cWtobNyBlASoD9tAhG/view?usp=sharing

**Comment by bcg-soyeon** [comment]
드라이브 요청 드렸습니다
