### ISSUE TITLE
설정 > 친구 초대하기 및 About 스크린 내 문구 수정 

### ISSUE THREAD

**Issue by hslee-afun** [alockwallet/app#12]
<img src="https://user-images.githubusercontent.com/83191583/130729820-1bb20a2a-ff7d-4b12-96f7-59417938ee23.jpeg" width="25%" height="25%">
<img src="https://user-images.githubusercontent.com/83191583/130729833-187cfb0f-3b6a-4e11-900b-d7ff33688b41.PNG" width="25%" height="25%">

블록체인 안심지갑 -> 에이락 월렛으로 수정 부탁드립니다.

**Comment by bcg-soyeon** [comment]
배포예정

**Comment by bcg-soyeon** [comment]
배포완료
