### ISSUE TITLE
설정 > About 스크린 내 별점 평가하기

### ISSUE THREAD

**Issue by hslee-afun** [alockwallet/app#13]
<img src="https://user-images.githubusercontent.com/83191583/130729833-187cfb0f-3b6a-4e11-900b-d7ff33688b41.PNG" width="25%" height="25%">

평가해주세요 버튼 기능이 없습니다.
각 플랫폼 별 스토어 이동 링크 기능 추가가 필요합니다.
수정에 기간이 오래 소요될 시, 삭제도 고려해주시길 바랍니다.

**Comment by bcg-soyeon** [comment]
링크 기능 추가 배포 예정

**Comment by bcg-soyeon** [comment]
배포완료
