### ISSUE TITLE
고객지원 > 도움말 스크린 내용 수정

### ISSUE THREAD

**Issue by hslee-afun** [alockwallet/app#14]
<img src="https://user-images.githubusercontent.com/83191583/130731354-55f056c5-3417-4832-a1c7-073998d02279.jpeg" width="33%" height="33%">

도움말에 해당하는 내용에 수정이 필요할 것 같아, 임시적으로 도움말 메뉴 삭제가 필요해 보입니다.
추후에 해당하는 내용 및 페이지 관련하여 공유드리도록 하겠습니다.

**Comment by bcg-soyeon** [comment]
배포예정

**Comment by bcg-soyeon** [comment]
배포완료
