### ISSUE TITLE
리워드> 전체리워드 조회 버튼, 리워드>고객사선택>고객사 리워드 조회 버튼의 기능 동작이 없습니다.

### ISSUE THREAD

**Issue by hw-afun** [alockwallet/app#15]
전체 리워드 조회 버튼과 고객사 리워드 조회 버튼을 눌렀을 때 아무런 이벤트가 없습니다.

![KakaoTalk_Photo_2021-08-26-10-34-30 002](https://user-images.githubusercontent.com/83437574/130886088-44d92cae-9fb9-43f7-ab54-9f3fe84fc54e.jpeg)
![KakaoTalk_Photo_2021-08-26-10-34-30 001](https://user-images.githubusercontent.com/83437574/130886102-ab64fd5f-3def-4867-aad8-a4e1f5d1989c.jpeg)

**Comment by bcg-soyeon** [comment]
두 버튼의 기능이 정의되어 있지 않아 기획이 필요합니다.

**Comment by hslee-afun** [comment]
현재 기획 및 기능이 정의되지 않았다면 임시로 삭제해주시면 감사하겠습니다!

**Comment by bcg-soyeon** [comment]
배포예정입니다!

**Comment by bcg-soyeon** [comment]
배포완료
