### ISSUE TITLE
리워드 > 고객사 선택 > 토큰 선택 > 리워드 지급 내역 스크린

### ISSUE THREAD

**Issue by hslee-afun** [alockwallet/app#16]
<img src="https://user-images.githubusercontent.com/83191583/130911533-dbd0b8e5-ab2d-4f91-a7d5-bec86625f6ea.jpg" width="50%" height="50%">

https://user-images.githubusercontent.com/83191583/130902762-d32ee88d-16e7-48df-809c-1dc5a0f9dae8.MP4

출금 하기 화면에서 리워드로 지급될 토큰의 정보를 볼 수 있는 페이지로 이동할 수 있는 버튼(링크) 추가 부탁드립니다.

해당 링크 url 값은 assets API response 값인 assets의 tokenSpec의 info을 사용해주시면 감사하겠습니다.

<img src="https://user-images.githubusercontent.com/83191583/130903294-21f155dc-cf81-4ab8-84f2-e48756e2c140.png" width="50%" height="50%">

**Comment by bcg-soyeon** [comment]
드림에서 퍼블리싱 진행 예정입니다.

**Comment by bcg-soyeon** [comment]
배포예정

**Comment by bcg-soyeon** [comment]
배포완료
