### ISSUE TITLE
status bar 색상 & safe area 처리

### ISSUE THREAD

**Issue by a-fun** [alockwallet/app#2]
![IMG_0DECDD98DA22-1](https://user-images.githubusercontent.com/83636017/125716361-4f4391ea-f8c8-4345-8adb-048e3dbe6838.jpeg)

**Comment by bcg-soyeon** [comment]
- iOS 배포 완료 (버전 4.0.5)

**Comment by bcg-soyeon** [comment]
- android 배포 완료 (버전 4.0.9)

**Comment by bcg-soyeon** [comment]
![김소연_20210719_164727_1](https://user-images.githubusercontent.com/87468359/126122549-d9468811-5d07-4c12-a522-1355627eb1ed.jpg)
4.0.9 apk 파일 확인해 보셨겠지만 status bar를 transparent처리 하면 
헤더 영역이 잡혀 들어가 각 페이지마다 margin을 잡아줘야 하여서 일단 revert하여 android 배포 하였습니다. (버전 4.1.0)
