### ISSUE TITLE
본인확인 페이지(Pass 이동 통신사 선택 화면 우측하단에도 (주)드림시큐리티 노출됩니다.

### ISSUE THREAD

**Issue by jeongsu-afun** [alockwallet/app#3]
![20210715_110705_329](https://user-images.githubusercontent.com/84124231/125716778-cee8f93d-b01f-4cad-a840-38ad2fbe912f.jpg)

**Comment by gomsugy** [comment]
이 문제는 오류가 아닙니다.
화면 하단의 로고는, (주)드림시큐리티 에서 제공하는 휴대폰본인확인서비스임을 나타냅니다.
저희 회사는 휴대폰본인확인서비스를 운영 중이며, 해당 로고는 휴대폰본인확인서비스 제공사의 로고입니다.
-드림시큐리티 우정민-
