### ISSUE TITLE
서비스 해지 시 반응없습니다.

### ISSUE THREAD

**Issue by jeongsu-afun** [alockwallet/app#4]
설정 -> 보안 -> 서비스 해지 -> 체크-> 체크 -> 해지복구단어 전체 입력 -> 다음 -> '네' 버튼 클릭 -> 무반응

잘못된 정보 입력 시 인증 실패라는 팝업은 정상 작동

**Comment by jeongsu-afun** [comment]
잘못된 정보 입력 시 인증 실패라는 팝업은 정상 작동

**Comment by bcg-soyeon** [comment]
기존 앱이 구독서비스 였기 때문에 존재하는 메뉴인데 삭제처리 하도록 하겠습니다.

**Comment by bcg-soyeon** [comment]
- 배포예정

**Comment by bcg-soyeon** [comment]
- iOS 배포 완료 (버전 4.0.5)

**Comment by bcg-soyeon** [comment]
- android 배포 완료 (버전 4.0.9)
