### ISSUE TITLE
설정>보안>PIN코드변경>PIN코드입력>PIN코드 변경  에서 오타있습니다.

### ISSUE THREAD

**Issue by hw-afun** [alockwallet/app#8]
'PIN코드 8자리를 입력해 주세요.' 라고 뜹니다. 6자리로 바꿔주세요.
![20210726_183501](https://user-images.githubusercontent.com/83437574/126968987-92087504-caef-42a5-b528-3a96d51a2ac5.jpg)

**Comment by bcg-soyeon** [comment]
안드로이드 배포 완료 (버전 코드 40103)
