### ISSUE TITLE
리워드>고객사리스트>고객사클릭>토큰클릭>리워드 지급내역의 테이블과 리워드 출금내역의 테이블 width가 다름

### ISSUE THREAD

**Issue by hw-afun** [alockwallet/app#9]
리워드 지급내역의 테이블과 리워드 출금내역의 테이블 width가 서로 달라 탭 이동시 움직이는것처럼 느껴집니다.
![Image from iOS](https://user-images.githubusercontent.com/83437574/130593421-239a2c71-8af1-45c4-8aac-88befcd8b763.png)
![Image from iOS (1)](https://user-images.githubusercontent.com/83437574/130593434-9641e402-f4dc-443b-960f-201689353534.png)

**Comment by bcg-soyeon** [comment]
배포 예정

**Comment by bcg-soyeon** [comment]
배포완료
